### PR TITLE
Update to stable kernel patch v4.8.11

### PR DESCRIPTION
**Pull request by dwrobel**
Update to RT PREEMPT kernel v4.8.11-rt7 and add patch to fix FIQ issue

### CODE REVIEW

**Comment by dwrobel** [comment]
For the record: this RT kernel doesn't require any extra parameters to fix the [FIQ issue](https://wiki.linuxfoundation.org/realtime/documentation/known_limitations).

**Comment by agrez** [comment]
Thanks dwrobel!

**Comment by agrez** [comment]
Hi @dwrobel. Just a quick update. I have added a separate yum repo for the RT-Preempt builds for FedBerry 25 (so they don't clash with our standard kernels). After a full dnf update, you will find the new fedberry-kernel-rt yum repo available. To enable:
```dnf config-manager --set-enabled fedberry-kernel-rt```

Please note: I have dropped all 4.9.x kernel builds from FedBerry 24 repos, as they have 'issues' (thus we have no RT-Preempt builds available for f24 at present). Maybe if people really want a RT_Preempt kernel under f24, I can add a 4.4.x rt build at some point.

**Comment by dwrobel** [comment]
That's great news, thanks.

**Pull request merged**
